### ISSUE TITLE
ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by stevenvachon** [isaacs/node-graceful-fs#115]
```
C:\projects\dotenv-prompt\node_modules\nyc\node_modules\graceful-fs\polyfills.js:21
  chdir.call(process, d)
        ^
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (C:\projects\dotenv-prompt\node_modules\nyc\node_modules\graceful-fs\polyfills.js:21:9)
    at Object.<anonymous> (C:\Users\appveyor\AppData\Local\Temp\1\769e47e6-92b8-4e5e-b839-4dc8b985af6d\child.js:3:11)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\projects\dotenv-prompt\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\projects\dotenv-prompt\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\projects\dotenv-prompt\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I'm not referencing "uv_chdir" anywhere.

My tests pass on OSX and Linux, but not Windows.

**Comment by stevenvachon** [comment]
The issue was caused by not escaping Windows `\\` in a concatenated string interpolation:
```js
const code = `process.chdir("${process.cwd()}");`
```
became
```js
const code = `process.chdir("${process.cwd().replace(/\\/g, "\\\\")}");`
```
