### ISSUE TITLE
parseQuery will be replaced with getOptions

### ISSUE THREAD

**Issue by anlexN** [isaacs/node-graceful-fs#117]
![loader-runner](https://user-images.githubusercontent.com/8686739/29410976-992bbbe2-8385-11e7-8927-09c58ea8980c.PNG)

**Comment by isaacs** [comment]
This isn't related to graceful-fs.  Did you mean to post this somewhere else?  Maybe in the webpack repo?

**Comment by anlexN** [comment]
graceful-fs also have this problem

**Comment by isaacs** [comment]
Graceful-fs does not ever call a method `parseQuery`.  What are you seeing that leads you to thikn that this is a graceful-fs bug?

**Comment by 3amSoftware** [comment]
@isaacs  This is what leads us to believe it's an issue with graceful-fs: https://github.com/webpack/loader-utils/issues/56

After adding "process.traceDeprecation = true" to the webpack.config.js as suggested, I get the following output:
 
(node:74503) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/foo/project/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/Users/foo/project/node_modules/babel-loader/lib/index.js:79:35)
    at LOADER_EXECUTION (/Users/foo/project/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/foo/project/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/foo/project/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/foo/project/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/foo/project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/foo/project/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/foo/project/node_modules/graceful-fs/**graceful-fs.js:78:16**
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:438:3)

I admit that this code is a little beyond my javascript understanding, but it appears to be calling a function somewhat anonymously. Perhaps that could be related to the loader-utils issue above. Could you have another look at it?

**Comment by isaacs** [comment]
Trace through the code.

Graceful-fs is just reading a file.  Babel-loader and loader-utils are doing stuff with that file's contents when the callback is called.  Graceful-fs isn't calling loaderUtils.parseQuery().  It's just calling the cb function that was passed to it.

Start at the top of the stack, not the bottom.
