### ISSUE TITLE
Weird issue with tap

### ISSUE THREAD

**Issue by meryn** [isaacs/node-graceful-fs#14]
test/open.js does `require("tap")`, yet installing tap locally results in a weird error.
But if you don't install tap locally, `require` won't work.
The work-around that I found is to do `npm link tap` to use the global install.
Maybe this could be put in the readme?

```
Mac-Mini:node-graceful-fs meryn$ npm install tap
tap@0.4.1 node_modules/tap
├── deep-equal@0.0.0
├── buffer-equal@0.0.0
├── mkdirp@0.3.5
├── slide@1.1.3
├── nopt@2.1.1 (abbrev@1.0.4)
├── difflet@0.2.3 (charm@0.0.8, traverse@0.6.3)
├── glob@3.1.21 (inherits@1.0.0, minimatch@0.2.12)
└── runforcover@0.0.2 (bunker@0.1.2)
Mac-Mini:node-graceful-fs meryn$ npm test

> graceful-fs@1.2.0 test /Users/meryn/Code/node-graceful-fs
> tap test/*.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/meryn/Code/node-graceful-fs/node_modules/tap/node_modules/glob/glob.js:39:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
Mac-Mini:node-graceful-fs meryn$ rm -rf node_modules/
Mac-Mini:node-graceful-fs meryn$ npm link tap
/Users/meryn/Code/node-graceful-fs/node_modules/tap -> /usr/local/lib/node_modules/tap
Mac-Mini:node-graceful-fs meryn$ npm test

> graceful-fs@1.2.0 test /Users/meryn/Code/node-graceful-fs
> tap test/*.js

ok test/open.js ....................................... 14/14
total ................................................. 14/14

ok
Mac-Mini:node-graceful-fs meryn$
```

**Comment by isaacs** [comment]
This was an npm bug which has since been fixed.
