### ISSUE TITLE
Cannot find module './clone.js'

### ISSUE THREAD

**Issue by mstallmo** [isaacs/node-graceful-fs#142]
I'm running into the following error when attempting to run my unit tests with jest. While this might be a problem with jest I noticed on the stack trace that I've pasted below that it was indicating graceful-fs specifically. I also noticed that you all just did a release around the same time my build started failing. 

```
Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mason/Workspace/coordinator/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
npm ERR! Test failed.  See above for more details.
```
Any help or a point in the right direction would be awesome! 

Thanks!

Update: formatting

**Comment by occurr** [comment]
I have been seeing this error since 4.1.12 was released on NPM (9 minutes ago)

**Comment by icarus-sullivan** [comment]
Same error here, looking at source code it looks like

`module.exports = clone`

is defined before

`function clone`

However with hoisting this shouldn't be an issue.

**Comment by hyperknot** [comment]
This broke firebase-tools https://github.com/firebase/firebase-tools/issues/993

**Comment by PseudoCoding** [comment]
Look at #139

**Comment by jreidgreer** [comment]
This is causing issues in PhantomJS `postinstall`

**Comment by dhindsa** [comment]
This broke CK-12 build too. Looks like babel-cli dependency via Chokidar.

**Comment by mstallmo** [comment]
Confirmed 4.1.13 fixes the break.

Thanks for the quick fix! 

Closing this issue.
