### ISSUE TITLE
Serverless broke because dependency on graceful-fs

### ISSUE THREAD

**Issue by chensjlv** [isaacs/node-graceful-fs#143]
Hi,

Seems like the new release is missing clone.js. And it broke new serverless installation and pretty sure other frameworks who depends on it. Here is the bug.

```
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> serverless@1.32.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js

Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/node_modules/fs-extra/lib/index.js:4:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by hyperknot** [comment]
Broke firebase-tools:
https://github.com/firebase/firebase-tools/issues/993

**Comment by PseudoCoding** [comment]
Look at #139

**Comment by chensjlv** [comment]
Seems like the new release fixed it.

Thanks!
