### ISSUE TITLE
cb.apply is not a function

### ISSUE THREAD

**Issue by tyler-johnson** [isaacs/node-graceful-fs#164]
Hi we are getting this error recently on our CI as well as other Linux machines in the office.

```
/home/travis/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^
TypeError: cb.apply is not a function
    at /home/travis/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
```

Not too sure how to debug this, happy to provide more details.

**Comment by tyler-johnson** [comment]
nevermind this is a duplicate of #158
