### ISSUE TITLE
Cannot find module graceful-fs

### ISSUE THREAD

**Issue by jakefuller1** [isaacs/node-graceful-fs#178]
Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\JB\AppData\Roaming\npm\node_modules\npm\lib\npm.js:19:13
    at Object.<anonymous> (C:\Users\JB\AppData\Roaming\npm\node_modules\npm\lib\npm.js:496:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

Tried uninstalling node & npm - 5 times
Tried installing different versions 12 times
rebooted each time
This is a Windows 10 installation
Can't run npm install get error above
can't re-install graceful-fs, get error above
I can see graceful-fs directory and files

**Comment by chamie** [comment]
Try another node version. Got this error on v15 (15.4.0), but not on v12( 12.16.1).

**Comment by coreyfarrell** [comment]
This error is not a bug in graceful-fs but in the application which uses graceful-fs - likely the package.json for the application or one of it's dependencies didn't install all required modules.
