### ISSUE TITLE
TypeError: Cannot redefine property: ReadStream

### ISSUE THREAD

**Issue by yolpsoftware** [isaacs/node-graceful-fs#191]
After updating my project to NodeJS 14.4.0, graceful-fs ungracefully throws

```
TypeError: Cannot redefine property: ReadStream
    at Function.defineProperty (<anonymous>)
    at Object.patch ([PATH]\node_modules\graceful-fs\graceful-fs.js:223:10)
    at Object.<anonymous> ([PATH\MYFILE.ts])
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile ([PATH]\node_modules\ts-node\src\index.ts:858:23)
    at internal/modules/cjs/loader.js:1220:10
    at Object..ts ([PATH]\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

It seems that line 223 is run twice, one with a callstack from loader.js, another one directly from the `gracefulfs.gracefulify(fs)` call in my code.

NodeJS: 14.4.0
Windows 10
graceful-fs: 4.2.4

**Comment by coreyfarrell** [comment]
This indicates something else has replaced the `fs.ReadStream` property with a non-configurable property or otherwise frozen `fs`.  I just tried the following on node.js 14.4.0 and 14.5.0:
```js
const gfs = require('graceful-fs');
const fs = gfs.gracefulify(require('fs'));
```

No exceptions from this.  Maybe you could find some additional information using `console.log(fs.ReadStream.toString())` - this might help you find what has locked the property.

IMO the exception you are seeing is a legitimate failure, graceful-fs should not suppress this error.

**Comment by yolpsoftware** [comment]
Finally came back to this project. Thanks for the hint, here's the output of the `console.log(fs.ReadStream.toString())`:

```
function ReadStream(path, options) {
  if (!(this instanceof ReadStream))
    return new ReadStream(path, options);

  // A little bit bigger buffer and water marks by default
  options = copyObject(getOptions(options, {}));
  if (options.highWaterMark === undefined)
    options.highWaterMark = 64 * 1024;

  // For backwards compat do not emit close on destroy.
  if (options.emitClose === undefined) {
    options.emitClose = false;
  }

  this[kFs] = options.fs || fs;

  if (typeof this[kFs].open !== 'function') {
    throw new ERR_INVALID_ARG_TYPE('options.fs.open', 'function',
                                   this[kFs].open);
  }

  if (typeof this[kFs].read !== 'function') {
    throw new ERR_INVALID_ARG_TYPE('options.fs.read', 'function',
                                   this[kFs].read);
  }

  if (typeof this[kFs].close !== 'function') {
    throw new ERR_INVALID_ARG_TYPE('options.fs.close', 'function',
                                   this[kFs].close);
  }

  Readable.call(this, options);

  // Path will be ignored when fd is specified, so it can be falsy
  this.path = toPathIfFileURL(path);
  this.fd = options.fd === undefined ? null : options.fd;
  this.flags = options.flags === undefined ? 'r' : options.flags;
  this.mode = options.mode === undefined ? 0o666 : options.mode;

  this.start = options.start;
  this.end = options.end;
  this.autoClose = options.autoClose === undefined ? true : options.autoClose;
  this.pos = undefined;
  this.bytesRead = 0;
  this.closed = false;
  this[kIsPerformingIO] = false;

  if (this.start !== undefined) {
    checkPosition(this.start, 'start');

    this.pos = this.start;
  }

  if (this.end === undefined) {
    this.end = Infinity;
  } else if (this.end !== Infinity) {
    checkPosition(this.end, 'end');

    if (this.start !== undefined && this.start > this.end) {
      throw new ERR_OUT_OF_RANGE(
        'start',
        `<= "end" (here: ${this.end})`,
        this.start
      );
    }
  }

  if (typeof this.fd !== 'number')
    this.open();

  this.on('end', function() {
    if (this.autoClose) {
      this.destroy();
    }
  });
}
```

Seems this is an older version of `lib/fs.js` from the `nodejs/node` repo. I'm using NodeJS 12.18.0, and here's my package.json:

```
{
  "name": "...",
  "version": "1.0.0",
  "description": "...",
  "main": "index.js",
  "scripts": {
    "start": "ts-node index.ts",
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "engines": {
    "node": "=12.18.2"
  },
  "engineScrict": true,
  "dependencies": {
    "@google-cloud/translate": "^4.1.1",
    "add": "^2.0.6",
    "axios": "^0.18.0",
    "better-sqlite3": "^5.4.0",
    "chalk": "^2.4.2",
    "cheerio": "^1.0.0-rc.3",
    "commander": "^2.20.0",
    "crypto": "^1.0.1",
    "csv-parser": "^2.3.3",
    "firebase-admin": "^7.4.0",
    "fs": "0.0.1-security",
    "fs-extra": "^8.0.1",
    "graceful-fs": "^4.2.2",
    "https-proxy-agent": "^2.2.1",
    "image-size": "^0.7.4",
    "js-yaml": "^3.13.1",
    "json-stable-stringify": "^1.0.1",
    "log-update": "^3.3.0",
    "mongodb": "^3.5.9",
    "mz": "^2.7.0",
    "node-fetch": "^2.3.0",
    "ora": "^3.4.0",
    "probe-image-size": "^4.1.1",
    "sharp": "^0.24.1",
    "svg-to-png": "^4.0.0",
    "tiny-async-pool": "^1.0.4",
    "unbzip2-stream": "^1.3.3",
    "xml-stream": "^0.4.5",
    "yarn": "^1.22.5"
  },
  "devDependencies": {
    "@types/better-sqlite3": "^5.2.3",
    "@types/cheerio": "^0.22.11",
    "@types/commander": "^2.12.2",
    "@types/fs-extra": "^7.0.0",
    "@types/graceful-fs": "^4.1.3",
    "@types/image-size": "^0.7.0",
    "@types/jest": "^24.0.12",
    "@types/js-yaml": "^3.12.1",
    "@types/json-stable-stringify": "^1.0.32",
    "@types/mz": "0.0.32",
    "@types/node": "^11.13.7",
    "@types/node-fetch": "^2.3.3",
    "@types/ora": "^3.2.0",
    "@types/sharp": "^0.24.0",
    "@types/unzip": "^0.1.1",
    "jest": "^24.7.1",
    "ts-jest": "^24.0.2",
    "ts-node": "^8.1.0",
    "typescript": "^3.9.7"
  }
}
```

**Comment by yolpsoftware** [comment]
Just noticed it might be connected to TypeScript. When using TypeScript 3.7.5, everything runs fine. This issue happens when TypeScript is at 3.9.7.

No idea why.

**Comment by coreyfarrell** [comment]
It could be the TypeScript implementation of `import * as fs from 'fs'` which is breaking the object.  Not sure if TypeScript will allow you to `import fs from 'fs'` (node.js provides the whole module via the default export).  You can do a test without using graceful-fs:
```js
import * as fs from 'fs';

let ReadStream = fs.ReadStream;
Object.defineProperty(fs, 'ReadStream', {
  get: function () {
    return ReadStream
  },
  set: function (val) {
    ReadStream = val
  },
  enumerable: true,
  configurable: true
});
```

Again maybe `import fs from 'fs'` will do better.  I'm closing this issue as I believe the bug is (or maybe was) in TypeScript.
