### ISSUE TITLE
SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned ENFILE (file table overflow)

### ISSUE THREAD

**Issue by mrcheidel** [isaacs/node-graceful-fs#198]
I find this error on Mac Retina testing the concurrency and using node/12.18.4 (with node/10.12.0 all run fine)

(libuv) kqueue(): Too many open files in system
tty.js:93
    throw new ERR_TTY_INIT_FAILED(ctx);
    ^

SystemError [ERR_TTY_INIT_FAILED]: TTY initialization failed: uv_tty_init returned ENFILE (file table overflow)
    at new WriteStream (tty.js:93:11)
    at createWritableStdioStream (internal/bootstrap/switches/is_main_thread.js:43:16)
    at process.getStderr [as stderr] (internal/bootstrap/switches/is_main_thread.js:129:12)
    at Socket._destroy (net.js:665:26)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at Socket.onReadableStreamEnd (net.js:635:12)
    at Socket.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_TTY_INIT_FAILED',
  info: {
    errno: -23,
    code: 'ENFILE',
    message: 'file table overflow',
    syscall: 'uv_tty_init'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

**Comment by coreyfarrell** [comment]
This looks like you ran out of system FD's during process startup.  This happens before graceful-fs could possible start.  Unfortunately this is not a recoverable condition.

Likely the difference between node.js versions is due to the new version using more FD's than the previous version.  I doubt this is a bug in node.js, likely just the new version of node.js requires one or two more FD's and you have always been right at the edge of exhausting your FD's.
