### ISSUE TITLE
eventually EMFILE error is thrown...

### ISSUE THREAD

**Issue by syberkitten** [isaacs/node-graceful-fs#20]
using graceful-js to serve videos via http, using createReadStream
eventually throws errors:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: accept EMFILE
    at errnoException (net.js:901:11)
    at TCP.onconnection (net.js:1159:24)

graceful allows the application to run a bit more, without it i get the error:
error on readstream:Error: EMFILE, open 'video.mp4'
after a few benchmarks:
ab -c 200 -n 200 http://127.0.0.1:8080/video.mp4

using node 10.0.15 (on centos linux)
here is the complete code (the http request handler is in the function
serveStream.

the error originates in the core modules as i mentioned above, simple replace
graceful with the original require('fs') and the error pops our very soon (after 2-3 ab tests)

```
var http = require('http');
var fs = require('graceful-fs');
//var fs = require('fs');
var util = require('util');
var version = "0.56";
var mediaPath = 'G:/movies';
mediaPath = '/media_iphone';

cache = {
	fileStat:{}	
}


function log(str,data){
	//console.log.apply(this,arguments);
	console.log("log:"+str);
	
}

function logError(str,data){
	//console.log.apply(this,arguments);
	console.log("error:"+str);

}

function logWarn(str,data){
	//console.log.apply(this,arguments);
	console.log("warn:"+str);
}



function contentTypeSelector(ctype){
	if (!contentTypes[ctype]) return contentTypes["default"];
	return contentTypes[ctype];
}


// todo: do authentication here
function checkHeadersAuth(req){
	var h = req.headers;
	
	if (req.url.indexOf("favicon")>-1) return false;
	return true;
	if (h["user-agent"].indexOf("Mozilla")==-1) { // invalid headers
		return true;
	}
	return true;
}

/*
returns a metadata object for logging each request)
*/
function collectRequestMeta(req){
	var o = req.headers;
	o.url = req.url;
	o.ip = req.connection.remoteAddress;
	return o;
}

function responseError404(res) {
	res.writeHead(404,{'content-type':contentTypeSelector('html')});
	res.end();
}


function response200(res,str){
	res.writeHead(200,{'content-type':contentTypeSelector('html')});
	res.end(str || "");
}



var contentTypes = {
	"default":"text/html",
	"video":"video/mp4",
	"text":"text/json",
	"html":"text/html"
}


var server = require('http').createServer(function (req,res){

	var filename,readStream;
	
	log("Got Request from url:"+req.url);
	
	//readStream.setEncoding('utf-8');
	if (!checkHeadersAuth(req)) {
		log("not authorized, exiting, ip:"+req.connection.remoteAddress);
		responseError404(res);
		return;
	}

	filename = mediaPath+req.url

	log("accessing filename:"+filename)
	if (!cache.fileStat[filename])  { // caching the file stat for later use
		log("loading file");
		fs.stat(filename,function(err,stat){
			if (err) {
				responseError404(res);
				err('File Not Found',{request:collectRequestMeta(req),filename:filename});
				return;
			} 
			cache.fileStat[filename] = stat;
			serveStream(req,res,cache.fileStat[filename],filename);			
		});
		return;
	} 
	log("getting file from cache");
	serveStream(req,res,cache.fileStat[filename],filename);

});

/*
serves the stream when we have the proper file 
and have not failed
*/
function serveStream(req,res,stat,filename) {
	log("serverStream()")
	var total = stat.size;
	var file,responseType;
	var header = {};
	if (req.headers['range']) {
		var range = req.headers.range;
		var parts = range.replace(/bytes=/, "").split("-");
		var partialstart = parts[0];
		var partialend = parts[1];

		var start = parseInt(partialstart, 10);
		var end = partialend ? parseInt(partialend, 10) : total-1;
		var chunksize = (end-start)+1;
		console.log('RANGE: ' + start + ' - ' + end + ' = ' + chunksize);
		file = fs.createReadStream(filename, {start: start, end: end,autoClose:false});
		header = { 'Content-Range': 'bytes ' + start + '-' + end + '/' + total, 'Accept-Ranges': 'bytes', 'Content-Length': chunksize, 'Content-Type': contentTypeSelector('video')};
		responseType = 206;
	} else {
		responseType = 200;		
		file = fs.createReadStream(filename,{autoClose:false,bufferSize:16*1024});
		header = { 'Content-Length': total, 'Content-Type': contentTypeSelector('video')};
	}


	file.on('open',function(fd){
		//log("opening stream:"+fd);
		res.writeHead(responseType, header);
		///file.pipe(res);	
	})
	file.on('close',function(){
		//log("closing stream");
		file.destroy();
		res.end();
	});
	file.on('end',function(){
		//log("ending stream");
		file.destroy();
	});
	file.on('error',function(msg){
		logError('error on readstream:'+msg);
	});

	file.pipe(res);

}

server.listen(8080);
//log('server started, scope:'+this,__filename+' version:'+version);	
log('server started, version:'+version);	


```

change "mediaPath" to your directory containing the video to serve
and run the ab test 4-5 times (stop each test after a few seconds (10-30) as it will try to get the whole video for it to end)

I'm serving videos sizes of 100-3000 mbs.

opened an issue (which was closed) at:
https://github.com/joyent/node/issues/6041

**Comment by isaacs** [comment]
Fixed on v4
