### ISSUE TITLE
broken when upgrade to nodejs 14.x

### ISSUE THREAD

**Issue by chaoyangnz** [isaacs/node-graceful-fs#212]
TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

      at ../../node_modules/graceful-fs/polyfills.js:139:39
      at patch (../../node_modules/graceful-fs/polyfills.js:141:5)
      at patch (../../node_modules/graceful-fs/graceful-fs.js:104:3)
      at Object.<anonymous> (../../node_modules/graceful-fs/graceful-fs.js:96:18)

**Comment by james-wallis** [comment]
@chaoyangnz did you fix this? I'm having the same issue.
