### ISSUE TITLE
Object prototype may only be an Object or null: undefined         at Function.setPrototypeOf

### ISSUE THREAD

**Issue by gnorbsl** [isaacs/node-graceful-fs#216]
I updated my dependencies, one of them is google-cloud/storage which seems to use this module.

```
TypeError: Object prototype may only be an Object or null: undefined
        at Function.setPrototypeOf (<anonymous>)

      at node_modules/graceful-fs/polyfills.js:139:39
      at patch (node_modules/graceful-fs/polyfills.js:141:5)
      at patch (node_modules/graceful-fs/graceful-fs.js:104:3)
      at Object.<anonymous> (node_modules/graceful-fs/graceful-fs.js:96:18)
      at Object.<anonymous> (node_modules/configstore/index.js:4:12)
```

Node 12

I can't really tell what is happening where though.

**Comment by paulofaria** [comment]
I have the same issue!

**Comment by gnorbsl** [comment]
@paulofaria Are you using google firebase storage too by chance? if so can you post here too:

https://github.com/googleapis/nodejs-storage/issues/1492

**Comment by paulofaria** [comment]
No, I believe my issue was very much a newbie error. I was trying to run a library that has `graceful-fs` as a dependency in the browser. I believe this library I mentioned is only supposed to run on node.js. My bad.

**Comment by swamifalgun** [comment]
I still am unable to solve this issue. Using the `@national-digital/gridsome-plugin-keep-processed-images` in my gridsome app triggers this error for me. @paulofaria could you point to a possible solution? thanks!

**Comment by wangjia184** [comment]
I  encounter the same error in rollup

**Comment by yoshixi** [comment]
> No, I believe my issue was very much a newbie error. I was trying to run a library that has `graceful-fs` as a dependency in the browser. I believe this library I mentioned is only supposed to run on node.js. My bad.

I agree.

**Comment by PavlosIsaris** [comment]
Is there any update on this issue?

**Comment by villarzz** [comment]
someone fixed it?

**Comment by hflcc** [comment]
> someone fixed it?

Try closing sourceMap.
