### ISSUE TITLE
NOT using gulp - primordials error

### ISSUE THREAD

**Issue by Daxcor69** [isaacs/node-graceful-fs#234]
I am using node 16.17.1
"graceful-fs": "^4.2.10",

when I load my application with nodemon I get 
```
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/home/brad/applications/admin_server/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/brad/applications/admin_server/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/brad/applications/admin_server/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```
All google talks about is the incompatibility with gulp. I am NOT using gulp. I have used this module so many times I just can't figure out what the issue is.

**Comment by Daxcor69** [comment]
This was due to a npm module   unzip.  Sorry for opening the issue.

**Comment by TomJarrett0** [comment]
What do you mean by npm module unzip?
