### ISSUE TITLE
Failed to use strict mode with NodeJS

### ISSUE THREAD

**Issue by jonDotsoy** [isaacs/node-graceful-fs#49]
```javascript
> node --use-strict --harmony_modules --harmony_proxies --harmony_arrow_functions --harmony --es_staging lib/cli.js

...\node_modules\graceful-fs\graceful-fs.js:80
        open(req.path, req.flags || "r", req.mode || 0777, req.cb)
                                                     ^^^^

SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (...\glob.js:39:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Test failed.  See above for more details.
```

I found a solution, replace `0777` to `777` in `graceful-fs.js:80` file.

**Comment by thisconnect** [comment]
Is that correct? becasue `0o777` octal seems to be `511`

**Comment by thisconnect** [comment]
yup others use `parseInt('0777', 8)` which returns `511` .

**Comment by jonDotsoy** [comment]
You're right, it is '511'. 

<http://stackoverflow.com/questions/20769023/using-nodejs-chmod-777-and-0777#comment31131761_20769157>

**Comment by isaacs** [comment]
This is already fixed on the latest release.  Please upgrade.

**Comment by jonDotsoy** [comment]
​Great!!​
