### ISSUE TITLE
Can't install graceful-fs

### ISSUE THREAD

**Issue by greenlaw110** [isaacs/node-graceful-fs#54]
```sh
luog@luog-Satellite-P50-A:~/p/xprj/xprj⟫ npm install graceful-fs
npm WARN install Couldn't install optional dependency: Unsupported
```

my nodejs and npm version:

```
luog@luog-Satellite-P50-A:~/p/xprj/xprj⟫ nodejs -v
v5.4.1
luog@luog-Satellite-P50-A:~/p/xprj/xprj⟫ npm -v
3.3.12
```

**Comment by SilverDFlame** [comment]
Looking further into the issue, because I'm also not able to install `graceful-fs`, it's a new dependency written by IsaacS, that npm isn't seeing right.

```
13:46:35 npm sill addNameRange number 2 { name: 'natives', range: '>=1.0.1 <2.0.0', hasData: true }
13:46:35 npm sill addNameRange versions [ 'natives', [] ]
13:46:35 npm verb stack TypeError: Cannot read property 'latest' of undefined
13:46:35 npm verb stack     at next (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:248:35)
13:46:35 npm verb stack     at setData (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:236:5)
13:46:35 npm verb stack     at RES (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
13:46:35 npm verb stack     at f (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/once/once.js:17:25)
13:46:35 npm verb stack     at fixName (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:29:5)
13:46:35 npm verb stack     at saved (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
13:46:35 npm verb stack     at /opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
13:46:35 npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
13:46:35 npm verb cwd /var/lib/jenkins/jobs/guest-connect-v1-build/workspace/public
13:46:35 npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
13:46:35 npm ERR! argv "/opt/nodejs/node-v4.4.3-linux-x64/bin/node" "/opt/nodejs/node-v4.4.3-linux-x64/bin/npm" "install" "--loglevel" "silly"
13:46:35 npm ERR! node v4.4.3
13:46:35 npm ERR! npm  v2.15.1
13:46:35 
13:46:35 npm ERR! Cannot read property 'latest' of undefined
13:46:35 npm ERR! 
13:46:35 npm ERR! If you need help, you may report this error at:
13:46:35 npm ERR!     <https://github.com/npm/npm/issues>
```

Notice on the second line, where it's talking about versions, the array of versions is empty. This is why the install is failing.

**Comment by isaacs** [comment]
@greenlaw110 Can you please run `npm i -ddd` or upload your `npm-debug.log` file somewhere?
